### ISSUE TITLE
OSM Update concatenates intersected way

### ISSUE THREAD

**Issue by jschleic** [lonvia/osgende#12]
There is another case, where an update leaves duplicate nodes in the segments table. The route.geom is split into a multilinestring although on a fresh import, it is a linestring (See [waymarked-trails-site#436](https://github.com/lonvia/waymarked-trails-site/issues/236))

The following new test scenario shows, what's wrong in segmenttable.feature:
<pre>
    Scenario: Add Y intersection to other intersected way
      Given a 0.0001 node grid
        | 1 | 2 | 3 | 4 | 5 |
        |   | 6 |   | 7 |   |
      And the osm data
        | id  | data      | tags |
        | W1  | 1,2,3,4,5 | |
        | W2  | 2,6       | |
        | W3  | 4,7       | |
        | R1  | W1        | HIKING |
        | R2  | W2        | HIKING |
      When constructing a RouteSegments table 'Hiking'
      Given an update of osm data
        | action | id | data      | tags |
        | A      | R3 | W3        | HIKING |
      When updating table Hiking
      Then table Hiking consists of rows
        | nodes      | ways | rels |
        | 1,2        | 1    | 1    |
        | 2,3,4      | 1    | 1    |
        | 4,5        | 1    | 1    |
        | 2,6        | 2    | 2    |
        | 4,7        | 3    | 3    |

>> Assertion Failed: ('1,2,3,4', '1', '1') not found in {('2,3,4', '1', '1'), ('4,5', '1', '1')}
</pre>
The same test passes when importing all three relations at once without update.

**Comment by jschleic** [comment]
And another scenario along the same lines:

<pre>
    Scenario: Add relation to the end of intersected way
      Given a 0.0001 node grid
        | 1 | 2 | 3 | 4 | 5 |
        | 6 |   |   | 7 |   |
      And the osm data
        | id  | data      | tags |
        | W1  | 1,2,3,4,5 | |
        | W2  | 1,6       | |
        | W3  | 4,7       | |
        | R1  | W1        | HIKING |
        | R3  | W3        | HIKING |
      When constructing a RouteSegments table 'Hiking'
      Given an update of osm data
        | action | id | data      | tags |
        | A      | R2 | W2        | HIKING |
      When updating table Hiking
      Then table Hiking consists of rows
        | nodes      | ways | rels |
        | 1,2,3,4    | 1    | 1    |
        | 4,5        | 1    | 1    |
        | 1,6        | 2    | 2    |
        | 4,7        | 3    | 3    |
</pre>

As a question for understanding the database structure: Why do intersections need to split the "long way" at all? As far as I understand the different segments are for rendering the overlay in different colors. But the color-coding of a relation only changes, if multiple relations overlap, not when they cross?

**Comment by lonvia** [comment]
Thanks for the test cases, that really helps. I had notices that there were still errors just hadn't identified them yet.

The original idea was to create a routable graph, although I never got as far as actually using it. The other apotential use-case is for optimised shield placement but that hasn't happened yet either.
